module.exports = {
    allStates : [
        "Andhra Pradesh",
        "Arunachal Pradesh",
        "Assam",
        "Bihar",
        "Chhattisgarh",
        "Goa",
        "Gujarat",
        "Haryana",
        "Himachal Pradesh",
        "Jammu and Kashmir",
        "Jharkhand",
        "Karnataka",
        "Kerala",
        "Madhya Pradesh",
        "Maharashtra",
        "Manipur",
        "Meghalaya",
        "Mizoram",
        "Nagaland",
        "Odish",
        "Punjab",
        "Rajasthan",
        "Sikkim",
        "Tamil Nadu",
        "Telangana",
        "Tripura",
        "Uttar Pradesh",
        "Uttarakhand",
        "West Bengal",
    ],

    colours : [
        "Black",
        "Grey",
        "Red",
        "Blue",
        "Orange",
        "White",
        "Brown",
        "Pink",
        "Yellow",
        "Green",
        "Purple",
        "Maroon",
        "Turquoise",
        "Cyan",
        "Navy blue",
        "Gold",
        "Tomato",
        "Teal",
        "Lime",
        "Cyan",
        "Wheat",
        "Salmon",
        "Olive",
        "Aqua",
        "Violet",
        "Chocolate",
        "Azure",
        "Sİlver",
        "Bronze",
        "Dark blue",
        "Navy",
        
      ]



}